# Alert explanation helper for CIS
from typing import Any, Dict
try:
    from .explainable import explain_alert_event
except Exception:
    explain_alert_event = None

ALERT_SEVERITY_DETAILS = {
    "HIGH": "Immediate attention required. This alert indicates a strong likelihood of an active threat.",
    "MEDIUM": "Action should be taken soon. This alert indicates suspicious activity that may escalate.",
    "LOW": "Monitor this activity. It may represent an early warning or benign anomaly.",
    "INFO": "Informational alert. Review the details and confirm whether any follow-up is needed.",
}

DEFAULT_ACTION = "Review the alert details and investigate the affected process. Isolate or rollback unauthorized activity if found."


def explain_alert(alert_payload: Dict[str, Any]) -> Dict[str, Any]:
    """Generate a human-readable explanation for an alert payload."""
    event = alert_payload.get("event", "unknown")
    severity = alert_payload.get("severity", "INFO").upper()
    actionable = alert_payload.get("actionable", {})
    rule_name = alert_payload.get("rule_name") or alert_payload.get("rule", None)

    summary = "A CIS alert was triggered for suspicious activity."
    root_cause = "The underlying cause is under investigation."
    impact = "Potential impact includes unauthorized file modification or ransomware encryption."
    recommended_action = actionable.get("what_to_do") or DEFAULT_ACTION
    confidence = "medium"

    if event == "counterfactual_trigger":
        summary = "The system detected a suspicious sequence of file operations and potential future encryption."
        root_cause = (
            "Suspicious process behavior was detected by the CIS causal inference engine. "
            "This often indicates ransomware-like encryption or unauthorized data modification."
        )
    elif rule_name:
        summary = f"Custom alert rule '{rule_name}' was triggered."
        root_cause = (
            "A configured detection rule matched current system state, meaning one or more monitored metrics exceeded expectations."
        )
    elif event != "unknown":
        summary = f"Alert event '{event}' was generated by the detection system."
        root_cause = (
            "Suspicious telemetry or heuristic behavior matched an alert condition."
        )

    details = []
    if alert_payload.get("immune_alarm"):
        details.append("Immune model detected abnormal behavior.")
    if alert_payload.get("heuristic_alarm"):
        details.append("Heuristic write threshold was exceeded.")
    if alert_payload.get("current_encryption") is not None:
        details.append(f"Encryption signal at {alert_payload['current_encryption']:.2f}.")
    if alert_payload.get("modified_files_count") is not None:
        details.append(f"Modified files count is {alert_payload['modified_files_count']}.")
    if rule_name:
        details.append(f"Triggered by rule: {rule_name}.")

    if details:
        root_cause = " ".join([root_cause] + details)

    if severity == "HIGH":
        confidence = "high"
    elif severity == "LOW":
        confidence = "low"

    explanation = {
        "summary": summary,
        "root_cause": root_cause,
        "impact": impact,
        "recommended_action": recommended_action,
        "confidence": confidence,
    }

    # Attach model-agnostic explanation if available
    try:
        if explain_alert_event is not None and isinstance(alert_payload, dict):
            event = alert_payload.get("event_data") or alert_payload.get("event") or {}
            # if event is a dict, pass it; else create dict wrapper
            evt = event if isinstance(event, dict) else {"event": event}
            ext = explain_alert_event(evt)
            explanation["feature_importance"] = ext.get("feature_importance")
            explanation["evidence"] = ext.get("evidence")
            explanation["model_confidence"] = ext.get("confidence")
    except Exception:
        pass

    return explanation


def annotate_alert(alert_payload: Dict[str, Any]) -> Dict[str, Any]:
    """Ensure the alert payload contains explanation metadata."""
    if not isinstance(alert_payload, dict):
        return alert_payload
    if "explanation" not in alert_payload or not isinstance(alert_payload["explanation"], dict):
        alert_payload["explanation"] = explain_alert(alert_payload)
    return alert_payload
